apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  occupation: {{ .Values.occupation | quote}}
  hosting: |-
    {{- range .Values.hosting }}
    - {{ . | title | quote }}
    {{- end }}